### PR TITLE
Test stale-action, PR 1 - with "fake CLA not signed" label

### PR DESCRIPTION
**Pull request by erlend-aasland**
Testing https://github.com/python/cpython/pull/30500 / https://github.com/python/core-workflow/issues/93

### CODE REVIEW

**Comment by hugovk** [comment]
Bump to explicitly reset activity timers.

**Comment by ambv** [comment]
Both your last comment here *and* on issue 18 (I'm not tagging it deliberately to not retrigger its activity) were made over 24 hours ago. Nothing happened so far. Let's wait a while longer, maybe the `stale` actions only run once a day?

**Comment by ambv** [comment]
Umm, I should have probably responded on the other PR :D Oh well.

**Comment by hugovk** [comment]
Haha yes, these comments have reset the activity timer on this PR :D

Well let's just leave them both as is (I won't reset the other), and let's comment on the upstream PR or issue in future :)

---

https://github.com/hugovk/cpython/runs/4769591131?check_suite_focus=true shows the cron did run last night (15 hours ago), and processed them correctly, for example:

```
  [#18] Days before pull request stale: 1
```

-> at the cron time there hadn't yet been one whole day of inactivity, so nothing happened yet, as expected.

**Comment by hugovk** [comment]
Test successful!

Closed as expected. Commenting here to see if the `stale` label will be removed, though it's not important.

**Pull request closed without merging**
